site_name: Envotate
site_description: Settings management using environment variables and type annotations.
site_url: https://github.com/jordaneremieff/envotate

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deeppurple
      accent: deeppurple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

repo_name: jordaneremieff/envotate
repo_url: https://github.com/jordaneremieff/envotate
edit_uri: ""

nav:
    - Introduction: "index.md"

markdown_extensions:
  - mkautodoc
  - pymdownx.highlight
  - pymdownx.superfences